DATASET:
  NAME: ADE20K
  ROOT: /home/paul/datasets/ADEChallengeData2016
  TRAIN: images/training
  VAL: images/validation
  NUM_CATEGORY: 1055

MODEL:
  ARCH: 19
  NUM_FEATURES: 512
  BACKBONE: vgg
  WITH_ATTRIBUTE: True
  ARM: False

TRAINING:
  EPOCH: 100
  BATCH_SIZE: 128

TESTING:
  BATCH_SIZE: 128
  CHECKPOINT: best
  TEN_CROPS: False