DATASET:
  NAME: ADE20K
  ROOT: /home/paul/datasets/ADEChallengeData2016
  TRAIN: images/training
  VAL: images/validation

MODEL:
  ARCH: 50
  NUM_FEATURES: 0
  CHECKPOINTS: ./checkpoints

TRAINING:
  EPOCH: 30
  BATCH_SIZE: 128
  LOG_DIR: ./logs
  WITH_ATTRIBUTE: True

TESTING:
  BATCH_SIZE: 64
  CHECKPOINT: 30
  TEN_CROPS: TRUE