DATASET:
  NAME: ADE20K
  ROOT: /home/paul/datasets/ADEChallengeData2016
  TRAIN: images/training
  VAL: images/validation

MODEL:
  ARCH: 50
  CHECKPOINTS: ./checkpoints

TRAINING:
  EPOCH: 100
  BATCH_SIZE: 128
  LOG_DIR: ./logs

TESTING:
  BATCH_SIZE: 64
  CHECKPOINT: 100
  TEN_CROPS: TRUE