DATASET:
  NAME: ADE20K
  ROOT: /home/paul/datasets/ADEChallengeData2016
  TRAIN: images/training
  VAL: images/validation
  NUM_CATEGORY: 1055

MODEL:
  ARCH: 101
  NUM_FEATURES: 2048
  BACKBONE: resnext
  WITH_ATTRIBUTE: True
  ARM: False

TRAINING:
  EPOCH: 100
  BATCH_SIZE: 16

TESTING:
  BATCH_SIZE: 4
  CHECKPOINT: best
  TEN_CROPS: True