DATASET:
  NAME: ADE20K
  ROOT: /home/paul/datasets/ADEChallengeData2016
  TRAIN: images/training
  VAL: images/validation

MODEL:
  ARCH: 50
  CHECKPOINTS: ./checkpoints

TRAINING:
  EPOCH: 50
  BATCH_SIZE: 64
  LOG_DIR: ./logs

VALIDATION:
  BATCH_SIZE: 64

TESTING:
  BATCH_SIZE: 64
  CHECKPOINT: 30
  TEN_CROPS: TRUE