DATASET:
  NAME: SUN397
  ROOT: /home/paul/datasets/SUN397
  TRAIN: train
  VAL: val

MODEL:
  ARCH: 50
  NUM_FEATURES: 0
  CHECKPOINTS: ./checkpoints

TRAINING:
  EPOCH: 100
  BATCH_SIZE: 128
  LOG_DIR: ./logs
  WITH_ATTRIBUTE: True

TESTING:
  BATCH_SIZE: 64
  CHECKPOINT: 30
  TEN_CROPS: True