DATASET:
  NAME: SUN397
  ROOT: /home/paul/datasets/SUN397
  TRAIN: train
  VAL: val
  NUM_CATEGORY: 397

MODEL:
  ARCH: 50
  NUM_FEATURES: 2048 #densenet=2208 512=vgg resnet=resnext=2048
  BACKBONE: resnet #vgg | resnet | resnext | densenet
  WITH_ATTRIBUTE: False
  ARM: False

TRAINING:
  EPOCH: 100
  BATCH_SIZE: 128

TESTING:
  BATCH_SIZE: 64
  CHECKPOINT: best
  TEN_CROPS: True