DATASET:
  NAME: SUN397
  ROOT: /home/paul/datasets/SUN397
  TRAIN: train
  VAL: val
  NUM_CATEGORY: 397

MODEL:
  ARCH: 19
  NUM_FEATURES: 512 #densenet=2208
  BACKBONE: vgg
  WITH_ATTRIBUTE: False
  ARM: False

TRAINING:
  EPOCH: 100
  BATCH_SIZE: 128

TESTING:
  BATCH_SIZE: 64
  CHECKPOINT: best
  TEN_CROPS: True