DATASET:
  NAME: SUN397
  ROOT: /home/paul/datasets/SUN397
  TRAIN: train
  VAL: val
  NUM_CATEGORY: 397

MODEL:
  ARCH: 50
  NUM_FEATURES: 2048
  CHECKPOINTS: ./checkpoints

TRAINING:
  EPOCH: 100
  BATCH_SIZE: 32
  LOG_DIR: ./logs
  WITH_ATTRIBUTE: False

TESTING:
  BATCH_SIZE: 32
  CHECKPOINT: 100
  TEN_CROPS: True