DATASET:
  NAME: SUN397
  ROOT: /home/paul/datasets/SUN397
  TRAIN: train
  VAL: val
  NUM_CATEGORY: 397

MODEL:
  ARCH: 101
  NUM_FEATURES: 2048
  BACKBONE: resnext
  WITH_ATTRIBUTE: False
  ARM: False

TRAINING:
  EPOCH: 100
  BATCH_SIZE: 128

TESTING:
  BATCH_SIZE: 128
  CHECKPOINT: 100
  TEN_CROPS: False